dist: trusty
sudo: required
language: node_js

node_js:
  - "9"
  - "8"

os:
  - linux


before_install:
  - sudo sysctl fs.inotify.max_user_watches=524288
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload
